dockerfiles/checkin/hotel2-master/HotelApp/urls.py
from django.conf.urls import url
from HotelApp import views
from HotelApp.views import hotelSearch
app_name = 'HotelApp'
urlpatterns = [
     url(r'^$', views.hotelindex, name='hotelindex'),
     url(r'^dashboard/$', views.userDash, name='userDash'),
     url(r'^hotels/(?P<pk>[0-9]+)/$', views.hoteldetails, name='hoteldetails'),
     url(r'^search$', hotelSearch.as_view(), name='hotelsearch'),
     url(r'^(?P<id>[0-9]+)/reviews/create$', views.reviewCreateView.as_view(), name='createreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.reviewUpdateView.as_view(), name='editreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.reviewDeleteView.as_view(), name='deletereview'),
     url(r'^partner/apply$', views.partnerCreateView.as_view(), name='newproposal'),

]

dockerfiles/checkin/hotel2-master/HotelProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from HotelApp import views
#from django_registration.views import RegistrationView
from django_registration.backends.one_step.views import RegistrationView
from HotelProject import settings
from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView


class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/HotelApp/user/'

urlpatterns = [
    url(r'^$', views.home , name = 'home'),
    url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^HotelApp/', include('HotelApp.urls')),
    url(r'^ManageHotels/', include('ManageHotels.urls')),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^Reservations/', include('Reservations.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^social/', include('allauth.urls')),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/login/$', LoginView.as_view(), name ='auth_login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name ='auth_logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockerfiles/checkin/hotel2-master/ManageHotels/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from ManageHotels import views
from ManageHotels.views import ChartData,ChartView

app_name = 'ManageHotels'

# Specifying all the urls for the Manage Hotels app which the partners will see .
# Allows for Creating Hotels , Editing them and photos , and adding rooms etc.
urlpatterns = [
     url(r'^$', views.home, name='home'),
     url(r'^newhotel$', views.HotelCreateView.as_view(), name='createhotel'),
     url(r'^yourhotels$', views.showhotels, name='showhotel'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/edit$', views.HotelUpdateView.as_view(), name='editHotel'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/bookings$', views.showreservations, name='hotelreservations'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/delete$', views.HotelDeleteView.as_view(), name='deleteHotel'),
     url(r'^yourhotels/bookings/(?P<pk>[0-9]+)/delete$', views.cancelbooking, name='removebooking'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/dashboard$', views.showdashboard, name='hoteldash'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/manage$', views.managehotel, name='managehotel'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/rooms$', views.showRoomsDash, name='showRoomsDash'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/rooms/add$', views.RoomCreateView.as_view(), name='addRoom'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/rooms/edit$', views.RoomUpdateView.as_view(), name='editRoom'),
     url(r'^yourhotels/(?P<pk>[0-9]+)/rooms/delete$', views.RoomDeleteView.as_view(), name='deleteRoom'),
     url(r'^yourhotels/(?P<id>[0-9]+)/upload$', views.BasicUploadView.as_view(), name='basicupload'),
     url(r'^yourhotels/(?P<id>[0-9]+)/photodash$', views.showphotodash, name='photodash'),
     url(r'^yourhotels/(?P<id>[0-9]+)/thumbnail$', views.editThumbnail, name='editThumb'),
     url(r'^yourhotels/(?P<id>[0-9]+)/deletephoto$', views.deletePhoto, name='deletephoto'),
     url(r'^yourhotels/(?P<id>[0-9]+)/charts$', ChartView.as_view(), name = 'partnercharts'),
     url(r'^yourhotels/(?P<id>[0-9]+)/chart/data$', ChartData.as_view()),


]

dockerfiles/checkin/hotel2-master/ManageHotels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from HotelApp.models import Hotels
# Stating the Photo model , and giving it a file field to allow photo uploads.
class Photo(models.Model):

    path = models.FileField()
    hotel = models.ForeignKey(Hotels)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Photo'

    def __str__(self):
         return self.hotel.Name

dockerfiles/checkin/hotel2-master/ManageHotels/forms.py
from django import forms
from ManageHotels.models import Photo

# Using djangos Model forms to create a form using a model.
class PhotoForm(forms.ModelForm):
 class Meta:
     model = Photo
     fields = ['path',]

dockerfiles/checkin/hotel2-master/ManageHotels/views.py
import datetime
from django.db.models import Sum
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.core.urlresolvers import reverse,reverse_lazy
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from django import forms
from HotelApp.models import Hotels,Review,Room
from ManageHotels.forms import PhotoForm
from ManageHotels.models import Photo
from django.views import generic,View
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.template import RequestContext
from Authorize.models import Partners
from Reservations.models import Reservation



# Show the Partner Homepage if the request is made by a partner.
def home(request):
    user = request.user
    partner = user.partners
    PartnerHotel = Hotels.objects.filter(Partner_id = partner.id).count()
    print (partner.id)
    if partner:
            context = {'Partner': partner,'NumHotel':PartnerHotel}
            return render(request,'ManageHotels/home.html',context)

    else:
        return HttpResponse("Error")

# Show the partner their hotels.
@login_required
def showhotels(request):
    user = request.user
    thepartner= Partners.objects.get(userID = user)
    hotels_list = Hotels.objects.filter(Partner=thepartner)
    context = {'Hotels': hotels_list}
    return render(request,'ManageHotels/yourhotels.html',context)

#Show the partner reservations for specific hotels.
def showreservations(request,pk):
    thehotel = Hotels.objects.get(id = pk)
    Bookings = Reservation.objects.filter(hotel= thehotel)
    context = {'reservations':Bookings,'hotel':thehotel}
    return render(request,'ManageHotels/viewbookings.html',context)

# Display a hotel dashboard enabling the partner to manage their hotels including add rooms
def showdashboard(request,pk):
    thehotel = Hotels.objects.get(id = pk)
    context = {'Hotel': thehotel}
    return render(request,'ManageHotels/hoteldash.html',context)


def managehotel(request,pk):
    thehotel = Hotels.objects.get(id = pk)
    context = {'Hotel': thehotel}
    return render(request,'ManageHotels/managehotel.html',context)

def showRoomsDash(request,pk):
    thehotel = Hotels.objects.get(id = pk)
    rooms = Room.objects.filter(hotel=thehotel)
    context = {'Hotel': thehotel,'rooms':rooms}
    return render(request,'ManageHotels/roomDash.html',context)

def showphotodash(request,id):
    thehotel = Hotels.objects.get(id = id)
    photos = Photo.objects.filter(hotel =thehotel)
    thumbnail = photos.first()
    context = {'Hotel': thehotel,'Photos':photos,'Thumbnail':thumbnail}
    return render(request,'ManageHotels/photoDash.html',context)
def editThumbnail(request,id):
    if request.method == 'POST' and request.FILES['thumb']:
        thumb = request.FILES['thumb']
        fs = FileSystemStorage()
        filename = fs.save(thumb.name,thumb)
        name = thumb.name
        thehotel = Hotels.objects.get(id = id)
        photos = Photo.objects.filter(hotel =thehotel)
        thumbnail = photos.first()
        thumbnail.path = name
        thumbnail.save()
        link = reverse('ManageHotels:photodash', args=[id])
        return HttpResponseRedirect(link)
def deletePhoto(request,id):
       photo = Photo.objects.get(id = id)
       hotel = photo.hotel
       photo.delete()
       link = reverse('ManageHotels:photodash', args=[hotel.id])
       return HttpResponseRedirect(link)
# Generate Create Update and delete views using django's Createview
class HotelCreateView(CreateView):

    model = Hotels
    fields = ['Name','Address','City','Country','TelephoneNumber','Description']
    def get_success_url(self):
        #hotelid = self.kwargs['id']
        #url = reverse('HotelApp:hoteldetails', args=[hotelid])
        url = reverse('ManageHotels:home')
        return url
    def form_valid(self, form):
        user = self.request.user
        thepartner= Partners.objects.get(userID = user)
        form.instance.Partner_id = thepartner.id
        return super(HotelCreateView, self).form_valid(form)
class HotelUpdateView(UpdateView):

    model = Hotels
    fields = ['Name','Address','City','Country','TelephoneNumber','Description']
    def get_success_url(self):
        hotelid = self.kwargs['pk']
        url = reverse('ManageHotels:photodash', args=[hotelid])
        return url
    def form_valid(self, form):
        return super(UpdateView, self).form_valid(form)

class HotelDeleteView(DeleteView):
    model = Hotels
    def get_success_url(self):
        url = reverse('ManageHotels:home')
        return url
    def form_valid(self, form):
        return super(HotelDeleteView, self).form_valid(form)

class RoomCreateView(CreateView):

    model = Room
    fields = ['RoomType','Capacity','BedOption','Price','View','TotalRooms']
    def get_success_url(self):
        hotelid = self.kwargs['pk']
        url = reverse('ManageHotels:showRoomsDash', args=[hotelid])
        return url

    def form_valid(self, form):
        form.instance.hotel_id = self.kwargs['pk']
        return super(RoomCreateView, self).form_valid(form)
class RoomUpdateView(UpdateView):

    model = Room
    fields = ['RoomType','Capacity','BedOption','Price','View','TotalRooms']
    def get_success_url(self):
        roomid = self.kwargs['pk']
        room= Room.objects.get(id = roomid)
        hotel = room.hotel
        hotelid = hotel.id
        url = reverse('ManageHotels:showRoomsDash', args=[hotelid])
        return url

    def form_valid(self, form):
        return super(RoomUpdateView, self).form_valid(form)


class RoomDeleteView(DeleteView):

    model = Room
    def get_success_url(self):
        roomid = self.kwargs['pk']
        room= Room.objects.get(id = roomid)
        hotel = room.hotel
        hotelid = hotel.id
        url = reverse('ManageHotels:showRoomsDash', args=[hotelid])
        return url

# use a django defined view to show the image upload.
#This view also handles post retrieving and returning a json response.
class BasicUploadView(View):
    def get(self,request,id):
        photos_list = Photo.objects.filter(hotel=id)
        return render(self.request, 'ManageHotels/uploadf.html',{'photos':photos_list,'hotelid':id})
    def post(self,request,id):

        form = PhotoForm(self.request.POST,self.request.FILES)


        if form.is_valid():
            photo = form.save(commit=False)
            hotel = Hotels.objects.get(id = id)
            photo.hotel = hotel
            photo.save()
            data = {'is_valid':True,'name':photo.path.name, 'url':photo.path.url}
        else:
            data = {is_valid:False}
        return JsonResponse(data)

class ChartView(View):
    def get(self,request,id):
        return render(request, 'ManageHotels/PartnerCharts.html')

#Using django rest to send data to he views.
class ChartData(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request,id, format=None):
        # Loads the hotel countires with a list of countries within which the partner operates
        # Get the number of Hotels in each country.
        HotelCountries = Hotels.objects.filter(Partner_id = id).values_list('Country', flat = True).distinct()
        count = []
        for Country in HotelCountries:
            count.append(Hotels.objects.filter(Country = Country).count())

        # Get the number of bookings made by each hotel
        HotelNames = Hotels.objects.filter(Partner_id = id).values_list('Name', flat = True)
        PartnerHotel = Hotels.objects.filter(Partner_id = id)
        bookings = []
        # calculate the amount of money each hotel has made this year.
        for Hotel in PartnerHotel:
            bookings.append(Reservation.objects.filter(hotel = Hotel).count())

        today = datetime.datetime.now()
        money = []
        for Hotel in PartnerHotel:

            money.append(Reservation.objects.filter(hotel = Hotel ,CheckOut__year = today.year).aggregate(sum=Sum('totalPrice'))['sum'])


        data = {"Countries":HotelCountries,"Count":count,"Hotels":HotelNames,"Bookings":bookings,"Money":money}
        print(PartnerHotel)
        return Response(data)
# Partners can cancel a booking made by a user.
def cancelbooking(request,pk):
    Booking = Reservation.objects.get(id = pk)
    hotelid = Booking.hotel.id
    Booking.delete()
    link = reverse('ManageHotels:hotelreservations', args=[hotelid])
    return HttpResponseRedirect(link)

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/Delete.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <form id="dropzone" class="dropzone" action="{% url 'ManageHotels:uploadPhoto' hotelid %}" method="POST">
    {%csrf_token%}

  </form>
  <button id="submit-all">
    Submit files
  </button>

{%endblock%}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/dropzone.js"></script>
<script type="text/javascript">

var DrZone = new Dropzone(document.getElementById("dropzone"),{

  autoProcessQueue:false,
  init: function(){
    var submitButton = document.querySelector("#submit-all")
    myDropzone = this;
    submitButton.addEventListener("click",function(){
      myDropzone.processQueue()
    })
  }

});







</script>
{%endblock%}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/home.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Displays the Partners Dashboard -->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Partner Home</div>



                <div class="panel-body">
                      <!--  partner id in link -->
                      <a href="{% url 'ManageHotels:showhotel'  %}" class="list-group-item">View Your Hotels</a>
                      <a href="newhotel" class="list-group-item">List a New Hotel</a>
                        <!--  partners Statistics are shown if the partner has atleast one hotel -->
                      {% if NumHotel > 0%}
                        <a href="{% url 'ManageHotels:partnercharts' Partner.id %}" class="list-group-item">View Statistics</a>
                      {% endif%}

                    </div>
                </div>
                <div class="panel-footel text-center">
                    Welcome {{user.username}} You are logged in!  </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/hoteldash.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Displays the Hotel Management Dashboard-->
<div class="container">

    <div class="row">

        <div class="col-md-8 col-md-offset-2">

            <div class="panel panel-default">
                <div class="panel-heading">Hotel Dashboard</div>



                <div class="panel-body">
                    <div class="list-group">
                      <!-- Partners can view reservations or manage an existing hotel-->
                      <a href="{% url 'ManageHotels:hotelreservations' Hotel.id  %}" class="list-group-item">View Your Reservations</a>
                      <a href="{% url 'ManageHotels:managehotel' Hotel.id %}" class="list-group-item">Manage Hotel</a>
                      
                    </div>
                </div>
                <div class="panel-footel text-center"></div>
            </div>
            <a class="btn btn-default pull-right" href="{% url 'ManageHotels:home' %}">Back</a>
        </div>
    </div>
</div>

<!-- else

  <h1> No Way.</h1>-->


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/managehotel.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="panel-body">
<!-- List the actions a Partner can perform on their hotels such as , Edit / Add rooms or delete hotel -->
  <div class="container">
    <div class="row">
      <!-- Partner can Edit a hotel and add images. -->
      <div class="col-xs-6 col-md-4">
          <a href="{% url 'ManageHotels:editHotel' Hotel.id %}" class="thumbnail">
            <img src="{% static "/images/new.png" %}" alt="..." />
          </a>
          <p class="text-center">
          <b>Edit Hotel {{Hotel.id}}</b>
          </p>
      </div>
        <!-- Partners can Add and edit rooms . -->
      <div class="col-xs-6 col-md-4">
        <a href="{% url 'ManageHotels:showRoomsDash' Hotel.id %}" class="thumbnail center-block">
          <img src="{% static "/images/room.png" %}" alt="..." />
        </a>
        <p class="text-center">
        <b>Rooms</b>
        </p>
      </div>

      <!-- Partners can delete Hotels. -->
      <div class="col-xs-6 col-md-4">
        <form action="{% url 'ManageHotels:deleteHotel' Hotel.id %}" method="post">
            {% csrf_token %}
        <button type="submit" class="thumbnail">
          <img src="{% static "/images/delete.png" %}" alt="..." />
        </button>
      </form>
        <p class="text-center">
          <b>Delete Hotel</b>
        </p>
      </div>
  </div>
  
    </div>

      <hr>
      <a class="btn btn-default pull-right" href="{% url 'ManageHotels:home' %}">Back</a>
  </div>

{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/photoDash.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<h1>Photos:</h1>
<br />
<!-- Partners can upload thumbnails for their hotels -->
 {% if Thumbnail %}
  <form method="POST" action="{% url 'ManageHotels:editThumb' Hotel.id %}" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="form-group">
      <label for="imagebox" class="">Thumbnail:</label>
        <p>Current Thumbnail: {{Thumbnail.path}}</p>
      <div class="col-10">

      <input  name="thumb" type="file" value=" {{Thumbnail.path}}" id="imagebox">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Edit Thumbnail</button>

</form>
  {% else %}
  <p> Please Upload a Photo to represent this hotels Thumbnail</p>
{% endif %}

  <hr />
<!-- Partners can add Room photos for their hotels and remove them -->
{% for photo in Photos|slice:"1:"%}
  <img class="img-thumbnail"src="{{MEDIA_URL}}{{photo.path}}" />
  <a class="btn btn btn-danger pull-right text-center" href="{% url 'ManageHotels:deletephoto' photo.id %}">Delete</a>
  <br />
  <hr />
  {%endfor%}

  <a href="{% url 'ManageHotels:basicupload' Hotel.id %}" class="btn btn-primary">Add Images</a>
  <a href="{% url 'ManageHotels:managehotel' Hotel.id %}" class="btn pull-right">Back</a>


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/roomDash.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}


<!-- Displays the Room dashboard -->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{Hotel.Name}} | Rooms</div>

                <div class="panel-body">

                <table class="table">
                    <thead>
                      <tr>
                        <th>Type</th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>

                <!-- Displays each room in a hotel allowing the partner to add , edit and delete them. -->
                        {%for room in rooms%}

                        <tr>
                          <td><a class="" href="#"> {{room.RoomType}}:</a></td>
                          <td></td>

                          <td><a class="btn btn-default pull-right" href="{% url 'ManageHotels:editRoom' room.id %}">Edit Room</a></td>
                          <form action="{% url 'ManageHotels:deleteRoom' room.id %}" method="post">
                              {% csrf_token %}
                          <td><button type="submit" class="btn btn-danger pull-right">Delete Room</button></td>
                          </form>
                        </tr>

                      {%endfor%}
                    </tbody>
                </table>
                <hr>
                <a class="btn btn-success pull-left" href="{% url 'ManageHotels:addRoom' Hotel.id %}">Add Room</a>
                </div>
                <hr>
                  <a class="btn pull-right" href="{% url 'ManageHotels:managehotel' Hotel.id %}">Back</a>
                <div class="panel-footel text-center"></div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/uploadf.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
<!-- The front "end" of the JavaScript which shows the uploaded photos to the  users-->
  <div class="panel-body">
  <button type="button" class="btn btn-primary js-upload-photos">
    <span class="glyphicon glyphicon-cloud-upload"></span> Upload Photos
  </button>

  <input id="fileupload" type="file" name="path" multiple style="display:none;" data-url="{% url 'ManageHotels:basicupload' hotelid  %}"
  data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

  <table id="gallery" class="table table-bordered">
    <thead>

      <tr>
        <th>
          Uploaded Photos:
        </th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photos %}
        <tr>
          <td>
            <a href="{{ photo.path.url }}">{{ photo.path.name }}</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'ManageHotels:photodash' hotelid %}" class="btn pull-right">Back</a>

  </div>
  <!-- Shows a progress bar when uploading is taking place.-->
  <div class="modal fade" id="modal-progress" data-backdrop="static" datakeyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">
              0%
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block scripts %}
<!-- Dependencies -->
<script
      src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
      integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
      crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.iframe-transport/1.0.1/jquery.iframe-transport.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.18.0/js/jquery.fileupload.js"></script>
<script src="{% static "/js/basic-upload.js" %}"></script>


{% endblock%}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/viewbookings.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <a class="btn btn-default pull-right" href="{% url 'ManageHotels:hoteldash' hotel.id %}">Back</a>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 ">


        <!-- Displays all the reservations for a selected hotel and all the reservation details.-->
        <h4>Reservations for {{hotel.Name}}: </h4>

        <br />


        {% for reservation in reservations%}

        <a class="btn btn-sm btn-danger pull-right" href="{% url 'ManageHotels:removebooking' reservation.id %}">Cancel</a>
          <h5><u>{{reservation.room.RoomType}}</u></h5>
          <p><mark>Guest Name :</mark>  {{reservation.guestFirstName}} {{reservation.guestLastName}}.  </p>
          <p><mark>Check-in Date :</mark> {{reservation.CheckIn}}.  </p>
          <p><mark>Check-out Date:</mark> {{reservation.CheckOut}}.  </p>
          <p><mark>Total Price :</mark> £{{reservation.totalPrice}}.  </p>

          <hr />
        {% endfor %}

    </div>
</div>
{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/ManageHotels/yourhotels.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="panel-body">
<!-- List All the Hotels belonging to the Signed in partner , Linking to the Hotel Dashboard of each Hotel -->
      <div class="list-group">

          {%for hotel in Hotels%}
            <a href="{% url 'ManageHotels:hoteldash' hotel.id %}" class="list-group-item">{{hotel.Name}}</a>

          {% endfor %}

      </div>
      <hr>
      <a class="btn btn-default pull-right" href="{% url 'ManageHotels:home' %}">Back</a>
  </div>

{% endblock %}