dockerfiles/checkin/hotel2-master/HotelApp/urls.py
from django.conf.urls import url
from HotelApp import views
from HotelApp.views import hotelSearch
app_name = 'HotelApp'
urlpatterns = [
     url(r'^$', views.hotelindex, name='hotelindex'),
     url(r'^dashboard/$', views.userDash, name='userDash'),
     url(r'^hotels/(?P<pk>[0-9]+)/$', views.hoteldetails, name='hoteldetails'),
     url(r'^search$', hotelSearch.as_view(), name='hotelsearch'),
     url(r'^(?P<id>[0-9]+)/reviews/create$', views.reviewCreateView.as_view(), name='createreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.reviewUpdateView.as_view(), name='editreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.reviewDeleteView.as_view(), name='deletereview'),
     url(r'^partner/apply$', views.partnerCreateView.as_view(), name='newproposal'),

]

dockerfiles/checkin/hotel2-master/HotelProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from HotelApp import views
#from django_registration.views import RegistrationView
from django_registration.backends.one_step.views import RegistrationView
from HotelProject import settings
from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView


class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/HotelApp/user/'

urlpatterns = [
    url(r'^$', views.home , name = 'home'),
    url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^HotelApp/', include('HotelApp.urls')),
    url(r'^ManageHotels/', include('ManageHotels.urls')),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^Reservations/', include('Reservations.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^social/', include('allauth.urls')),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/login/$', LoginView.as_view(), name ='auth_login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name ='auth_logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockerfiles/checkin/hotel2-master/Reservations/urls.py
from django.conf.urls import url
from Reservations import views
from Reservations.views import GeneratePDF

# Sets the namespace that can be referred to throughout the django project.
app_name = 'Reservations'
#Urls in regular expression format trigger a view when a url is matched.
urlpatterns = [

    url(r'^book/(?P<hotelid>[0-9]+)/(?P<roomid>[0-9]+)$', views.bookRoom, name='bookroom'),
    url(r"^book/new/(?P<roomid>[0-9]+)/(?P<hotelid>[0-9]+)/(?P<checkin>(\d{4}-\d{2}-\d{2}))/(?P<checkout>(\d{4}-\d{2}-\d{2}))/(?P<totalcost>[0-9]+)$"
    , views.storeBooking, name='newbooking'),
    url(r'^mybookings/$', views.mybookings, name='viewbookings'),
    url(r'^mybookings/cancel/(?P<id>[0-9]+)$', views.cancelbooking, name='cancelbooking'),
    url(r'^mybookings/(?P<id>[0-9]+)/pdf$', GeneratePDF.as_view(), name='gpdf'),
    url(r'^mybookings/sns$',views.bookingsns, name ='bookingsns'),

]

dockerfiles/checkin/hotel2-master/Reservations/models.py
#Import the required Models (Usually foreing keys)
from django.db import models
from HotelApp.models import Hotels,Room
from django.contrib.auth.models import User
#Create a Reservation Model which stores booking details
class Reservation(models.Model):
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    guestFirstName = models.CharField(max_length  = 255)
    guestLastName = models.CharField(max_length  = 255)
    CheckIn = models.DateField()
    CheckOut = models.DateField()
    totalPrice = models.IntegerField(default = 0)

    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
         return self.guestLastName

dockerfiles/checkin/hotel2-master/Reservations/views.py
import datetime,os
from django import forms
from django.shortcuts import render
from django.core.urlresolvers import reverse,reverse_lazy
from django.core.signing import Signer
from django.http import HttpResponse,HttpResponseRedirect
from django.db.models import Q
from HotelApp.models import Hotels,Room,Proposal
from Authorize.models import UserRole
from ManageHotels.models import Photo
from Reservations.models import Reservation
from django.core.files.storage import FileSystemStorage
from django.views import View
from django.template.loader import get_template
from .utils import render_to_pdf
from rest_framework.decorators import api_view
from django.views.decorators.csrf import csrf_exempt
import boto3,botocore,json
from xhtml2pdf import pisa
ACCESS='AKIAIZGUB7EMMDIMH7CA'
SECRET='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'
region='us-east-1'
import MailConfig as MUE_Config
import MailUtils
import MySQLdb
conn = MySQLdb.connect('10.0.2.239','root','Priya@123','airbnb')
curs = conn.cursor()

## Generates a PDF using the render help function and outputs it as invoice.html
class GeneratePDF(View):
    def get(self,request, *args, **kwargs):
        booking = Reservation.objects.get(id= self.kwargs['id'])
        template = get_template('invoice.html')
        context = {"booking":booking}
        html = template.render(context)
        pdf = render_to_pdf('invoice.html', context)
	outputFilename=os.path.join("/tmp/","invoice.pdf")
	resultFile = open(outputFilename, "w+b")
	pisaStatus = pisa.CreatePDF(html,dest=resultFile)
	resultFile.close() 
#	pisa.CreatePDF(StringIO(html.encode('utf-8')), pdffile)
        files = []
        to = []
        files.append(outputFilename)
        email_query = "select email from auth_user a join Reservations_reservation b on a.id=b.user_id where a.id = '%s'"%(self.kwargs['id'])
        curs.execute(email_query)
        to_email = curs.fetchall()
        to.append(to_email[0][0])
#        print outputFilename
#        print files
#        print to
        MailUtils.send_mail(MUE_Config.MailConfig['auth'], MUE_Config.MailConfig['from'],to ,MUE_Config.MailConfig['subject'],MUE_Config.MailConfig['content'], None, files,cc=MUE_Config.MailConfig['cc'])

#	pdfile=open("PDF_BOOKING%s.pdf"%(self.kwargs['id']))
#	filename="PDF_BOOKING%s.pdf"%(self.kwargs['id'])
	s3=boto3.client('s3',aws_access_key_id=ACCESS,aws_secret_access_key=SECRET,region_name=region,config=boto3.session.Config(signature_version='s3v4'))
#        return HttpResponse(pdf,content_type='application/pdf')
	response = HttpResponse(pdf, content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="BookingReceipt.pdf"'
	s3.upload_file(outputFilename,'airbnbgokulb',self.kwargs['id']+'BookingReceipt.pdf')
	return response


@api_view(['POST'])
@csrf_exempt
def bookingsns(request):
	print request
	if request.method=='POST':
		received_json_data=json.loads(request.body)
		print received_json_data
		topic="arn:aws:sns:us-east-1:165910365825:bookingconfirmed"
		if received_json_data['Type']=='SubscriptionConfirmation':
			Token_Received=received_json_data['Token']
			snsclient=boto3.client('sns',aws_access_key_id=ACCESS,aws_secret_access_key=SECRET,region_name=region,config=boto3.session.Config(signature_version='s3v4'))
			response = snsclient.confirm_subscription(TopicArn=topic,Token=Token_Received, AuthenticateOnUnsubscribe='true')
			return HttpResponse("200 OK")
		elif received_json_data['Type']=='Notification':
			a=received_json_data
			MessageReceived = json.loads(a['Message'])
			BUCKET_ARN= MessageReceived['Records'][0]['s3']['bucket']['arn']
			BUCKET_NAME=MessageReceived['Records'][0]['s3']['bucket']['name']
			KEY= str(MessageReceived['Records'][0]['s3']['object']['key'])
			s3=boto3.client('s3',aws_access_key_id=ACCESS,aws_secret_access_key=SECRET,region_name=region,config=boto3.session.Config(signature_version='s3v4'))
			print BUCKET_ARN,BUCKET_NAME,KEY
			try:
				s3.download_file(BUCKET_NAME,KEY,KEY)
		#		s3.download_file('airbnbgokul','2invoice.pdf','2invoice.pdf')
#				sendmail()
			except botocore.exceptions.ClientError as e:
				if e.response['Error']['Code']=="404":
					print("The object does not exist")
				else:
					raise
			return HttpResponse("200 OK")


## Works out how long the user is staying in a hotel for also working out the total cost.
def bookRoom(request,hotelid,roomid):

    FirstDate = request.session['checkin']
    SecDate =  request.session['checkout']

    Checkin = datetime.datetime.strptime(FirstDate, "%Y-%m-%d").date()
    Checkout = datetime.datetime.strptime(SecDate, "%Y-%m-%d").date()
    timedeltaSum = Checkout - Checkin

    StayDuration = timedeltaSum.days

    Hotel = Hotels.objects.get(id = hotelid)
    theRoom = Room.objects.get(id = roomid)

    price = theRoom.Price
    TotalCost = StayDuration * price


    context = {'checkin': Checkin, 'checkout':Checkout,'stayduration':StayDuration,'hotel':Hotel,'room':theRoom,'price':price,
    'totalcost':TotalCost}
    return render(request, 'Reservations/booking.html', context)

# Stores the confirmed booking  into the database
def storeBooking(request,hotelid,roomid,checkin,checkout,totalcost):
    if request.method == 'POST':

        Firstname = request.POST.get('firstname')
        Lastname = request.POST.get('lastname')
        user = request.user
        hotel = Hotels.objects.get(id = hotelid)
        room = Room.objects.get(id = roomid)
        cost = totalcost
        newReservation = Reservation()
        newReservation.hotel = hotel
        newReservation.room = room
        newReservation.user = user
        newReservation.guestFirstName = Firstname
        newReservation.guestLastName = Lastname
        newReservation.CheckIn = checkin
        newReservation.CheckOut = checkout
        newReservation.totalPrice = cost
        newReservation.save()
        #Deletes the session variables.
        del request.session['checkin']
        del request.session['checkout']
        link = reverse('HotelApp:userDash')
        return HttpResponseRedirect(link)

    else:
        url = reverse('HotelApp:userDash')
        return url

#Shows the user thier previous bookings.
def mybookings(request):
    bookings = Reservation.objects.filter(user = request.user)
    context = {'bookings':bookings}
    return render(request, 'Reservations/mybookings.html', context)


# Allows a user to cancel their previous bookings , deleting a booking onclick.
def cancelbooking(request,id):
    booking = Reservation.objects.get(id = id)
    booking.delete()
    currentuser = request.user
    Role = UserRole.objects.get(user = request.user)
    link = reverse('Reservations:viewbookings')
    return HttpResponseRedirect(link)

dockerfiles/checkin/hotel2-master/Reservations/templates/Reservations/booking.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
          <!-- Display all the details about the users reservation before confirmation-->
          <h1>Check-In: <small>Make a Booking</small></h1>
      </div>
      <center>
          <h1>{{hotel.Name}}</h1>
          <small>{{hotel.Address}},{{hotel.City}},{{hotel.Country}}</small>
      </center>
      <br />
      <center>
          <h2><u>Summary</u></h2>
      </center>
      <br />

      <center>

          <h5>Check-in:</h5><p><b>{{checkin}} </b></p>


      </center>



      <center>

          <h5>Check-out:</h5><p><b>{{checkout}}  </b></p>


      </center>
      <center>

          <h5>Stay:</h5><p>{{stayduration}} Nights.</p>  </center>

      <hr />
      <center>

          <h2><u>Your Room: {{room.RoomType}}</u></h2>
     </center>

      <center>
           <b>Max Occupents:</b><p>{{room.Capacity}} people. </p>
           <b>Beds Provided:</b><p> {{room.BedOption}}.</p>
           <b>Room View:</b><p> {{room.View}}.</p>
           <b>Price Per Night:</b><p> £{{room.Price}}.</p>

           <p> £{{room.Price}} x {{stayduration}} Nights </p>
           <b class="lead">Total Price: <u>£{{totalcost}}</u></b>
      </center>

      <br />
      <hr />

    <!-- after reviewing the Reservation details the user enters their First and Last name to make a booking -->
      <form method="POST"  action="{% url 'Reservations:newbooking' room.id hotel.id checkin checkout totalcost  %}">
          {% csrf_token %}
        <center>
          <div class="form-group row">
              <div class="col-xs-6">
                  <label for="first">Guest First Name:</label>
                  <input class="form-control pull-left" name="firstname" id="first" type="text" required="First Name" />
              </div>
              <div class="col-xs-6">
                  <label for="first">Guest Last Name:</label>
                  <input class="form-control pull-right" name="lastname" id="last" type="text" required="Last Name" />
              </div>
          </div>

          <hr />
          <button type="submit" class="btn btn-success">Book Now!</button>
       </center>

     </form>


  </div>

</div>

{% endblock %}

dockerfiles/checkin/hotel2-master/Reservations/templates/Reservations/mybookings.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
<a class="btn btn-default pull-right" href="{% url 'HotelApp:userDash' %}">Back</a>
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">



      <h4>My Bookings:</h4>

      <br />
<!-- Loads all of the Current users reservations in a list and displays all  the details -->

      {%for booking in bookings%}

        <a class="btn btn-sm btn-danger pull-right" href="{% url 'Reservations:cancelbooking' booking.id %}">Cancel</a>
        <a  class="btn btn-sm btn-default pull-right "href="{% url 'Reservations:gpdf' booking.id %}">Download PDF</a>
        <h5><u> {{booking.hotel.Name}}</u></h5>
        <p><mark>Room Type :</mark> {{booking.room.RoomType}}.  </p>
        <p><mark>Guest Name :</mark>  {{booking.guestFirstName}} {{booking.guestLastName}}.  </p>
        <p><mark>Check-in Date :</mark> {{booking.CheckIn}}.  </p>
        <p><mark>Check-out Date:</mark> {{booking.CheckOut}}.  </p>
        <p><mark>Total Price :</mark> £{{booking.totalPrice}}.  </p>


        <hr />
      {%endfor%}

    </div>
  </div>
{% endblock %}