dockerfiles/checkin/hotel2-master/Authorize/urls.py
from django.conf.urls import url
from HotelApp import views
from Authorize import views
# Url patters for authorization such as accepting , deleting and removing a partner.
app_name = 'Authorize'
urlpatterns = [
         url(r'^$', views.displayDash, name='displayDash'),
         url(r'^admindash$', views.displayAdminDash, name='admindash'),
         url(r'^admindash/proposals$', views.showProposals, name='showproposals'),
         url(r'^admindash/partners$', views.showPartners, name='showpartners'),
         url(r'^admindash/partners/(?P<id>[0-9]+)/remove$', views.removePartner, name='removepartner'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/accept$', views.acceptProposals, name='acceptproposal'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/decline$', views.declineProposals, name='declineproposal'),
         url(r'^partner/checkstatus$', views.checkstatus, name='checkproposal'),
]

dockerfiles/checkin/hotel2-master/HotelApp/urls.py
from django.conf.urls import url
from HotelApp import views
from HotelApp.views import hotelSearch
app_name = 'HotelApp'
urlpatterns = [
     url(r'^$', views.hotelindex, name='hotelindex'),
     url(r'^dashboard/$', views.userDash, name='userDash'),
     url(r'^hotels/(?P<pk>[0-9]+)/$', views.hoteldetails, name='hoteldetails'),
     url(r'^search$', hotelSearch.as_view(), name='hotelsearch'),
     url(r'^(?P<id>[0-9]+)/reviews/create$', views.reviewCreateView.as_view(), name='createreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.reviewUpdateView.as_view(), name='editreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.reviewDeleteView.as_view(), name='deletereview'),
     url(r'^partner/apply$', views.partnerCreateView.as_view(), name='newproposal'),

]

dockerfiles/checkin/hotel2-master/HotelProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from HotelApp import views
#from django_registration.views import RegistrationView
from django_registration.backends.one_step.views import RegistrationView
from HotelProject import settings
from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView


class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/HotelApp/user/'

urlpatterns = [
    url(r'^$', views.home , name = 'home'),
    url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^HotelApp/', include('HotelApp.urls')),
    url(r'^ManageHotels/', include('ManageHotels.urls')),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^Reservations/', include('Reservations.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^social/', include('allauth.urls')),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/login/$', LoginView.as_view(), name ='auth_login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name ='auth_logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockerfiles/checkin/hotel2-master/Authorize/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save

# Defines the roles on this website : Admin , Partner and user.
class Role(models.Model):
    RoleName = models.CharField(max_length  = 255)


    def __str__(self):
         return self.RoleName

# Used to restrict access to certain parts of the website, automaticaly makes each created user a customer.
class UserRole(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roleid = models.IntegerField(default = 3)
@receiver(post_save, sender=User)
def set_user(sender,instance,created,**kwargs):
    if created:
        UserRole.objects.create(user=instance)
@receiver(post_save, sender=User)
def save_set(sender,instance,**kwargs):
    instance.userrole.save()


    def __str__(self):
         return self.RoleName
# The partners model can store and query regarding partners
class Partners(models.Model):
    userID = models.OneToOneField(User, on_delete=models.CASCADE)
    CompanyName = models.CharField(max_length  = 255)
    CompanyEmail = models.EmailField(max_length  = 254)
    HQAddress = models.CharField(max_length  = 255)
    class Meta:
        verbose_name_plural = 'Partners'

    def __str__(self):
         return self.CompanyName

dockerfiles/checkin/hotel2-master/Authorize/views.py
from django.shortcuts import render
from django.http import HttpResponse
from Authorize.models import Role,UserRole
from django.core.urlresolvers import reverse,reverse_lazy
from django.http import HttpResponse,HttpResponseRedirect
from HotelApp.models import Proposal
from Authorize.models import Partners

# Displays the appropriate dashboard for each type of user.
def displayDash(request):
    user = request.user
    if user.userrole.roleid == 3:
        link = reverse('HotelApp:userDash')
        return HttpResponseRedirect(link)
    elif user.userrole.roleid == 4:
            link = reverse('ManageHotels:home')
            return HttpResponseRedirect(link)
    elif user.userrole.roleid == 2:
        link = reverse('Authorize:admindash')
        return HttpResponseRedirect(link)
#
def displayAdminDash(request):
    return render(request,'Authorize/admindash.html')
# Show partners , Accept proposals and remove partners.
def showProposals(request):
    proposal_list = Proposal.objects.all()
    context = {'proposals': proposal_list}
    return render(request, 'Authorize/proposals.html', context)
def showPartners(request):
    partner_list = Partners.objects.all()
    context = {'partners': partner_list}
    return render(request, 'Authorize/partners.html', context)
def removePartner(request,id):
    partner = Partners.objects.get(id = id)
    userid = partner.userID
    role = UserRole.objects.get(user = userid)
    role.roleid = 3
    role.save()
    partner.delete()

    link = reverse('Authorize:showpartners')
    return HttpResponseRedirect(link)
    #Accepts a partner and inputs them into the partners database aswell
    #as changing the role id to reflect this .
def acceptProposals(request,id):
    proposal = Proposal.objects.get(id = id)
    user = proposal.user
    newpartner = Partners()
    newpartner.userID = user
    newpartner.CompanyName = proposal.CompanyName
    newpartner.CompanyEmail = proposal.CompanyEmail
    newpartner.HQAddress = proposal.HQAddress
    newpartner.save()
    updaterole = UserRole.objects.get(user = user)
    updaterole.roleid = 4
    updaterole.save()
    proposal.delete()
    link = reverse('Authorize:showproposals')
    return HttpResponseRedirect(link)
def declineProposals(request,id):
    proposal = Proposal.objects.get(id = id)
    proposal.delete()
    link = reverse('Authorize:showproposals')
    return HttpResponseRedirect(link)

#  A user can check the status of their application
def checkstatus(request):
    proposal_list = Proposal.objects.filter(user = request.user)
    context = {'proposal': proposal_list}
    return render(request, 'Authorize/checkstatus.html', context)

dockerfiles/checkin/hotel2-master/templates/django_registration/Authorize/admindash.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}



<!-- Displays the Admin Dashboard -->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Admin Dashboard</div>



                <div class="panel-body">
                    <div class="list-group">
                      <!--  partner id in link -->
                      <a href="{% url 'Authorize:showproposals'  %}" class="list-group-item">Partner Requests</a>
                      <a href="{% url 'Authorize:showpartners'  %}" class="list-group-item">View Partners</a>


                    </div>
                </div>
                <div class="panel-footel text-center">
                    Welcome {{user.username}} You are logged in!  </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/Authorize/checkstatus.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Users can check their proposal status on this page -->
          {% if proposal %}
          <p>
              {{user.username}} -  You're proposal is currently being reviewed , we aim to get back to you shortly.
          </p>

        {% else %}
        <p>
          {{user.username}} you have no pending proposals.
        </p>

        {% endif %}

 <a href="{% url 'HotelApp:userDash'  %}" class="btn">Back to Dashboard.</a>

{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/Authorize/partners.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <h3 class="text-center">All Partners</h3>
                <!-- Displays a list of all the partners of Check-In.com and displays a Remove Button next to each -->
                    {% for partner in partners%}
                      <li class="list-group-item text-center">
                        {{partner.CompanyName}} <a class="btn btn-sm btn-danger pull-right" href="{% url 'Authorize:removepartner' partner.id %}">Remove</a>
                      </li>

                    {% endfor %}

              </div>

              <a href="{% url 'Authorize:admindash'  %}" class="btn btn-info">Back to Dashboard.</a>

          </div>
      </div>
  </div>

{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/Authorize/proposals.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}


  <h3>Partner Requests from Users:</h3>
  <ul>


    <table class="table">

      <thead>
        <tr>
        <th>Company Name</th>
        <th>Email</th>
        <th>HQ Address</th>
        <th>Vision</th>
        </tr>
      </thead>
      <tbody>

            <!-- Displays a list of all the partner Proposals sent to Check-In.com and an Accept/Refuse Button -->
          {% for proposal in proposals%}

            <tr>
              <td><a class="" href="#">{{proposal.CompanyName}}</a></td>
              <td>{{proposal.CompanyEmail}}</td>
              <td>{{proposal.HQAddress}}</td>
              <td>{{proposal.Vision}}</td>

                  <td><a class="btn btn-success pull-right" href="{% url 'Authorize:acceptproposal' proposal.id  %}">Accept</a></td>
                  <td><a class="btn btn-danger pull-right" href="{% url 'Authorize:declineproposal' proposal.id  %}">Refuse</a></td>


            </tr>

          {% endfor%}
     </tbody>
 </table>

  <a href="{% url 'Authorize:admindash'  %}" class="btn btn-info">Back to Dashboard.</a>







{% endblock %}