dockerfiles/checkin/hotel2-master/Authorize/urls.py
from django.conf.urls import url
from HotelApp import views
from Authorize import views
# Url patters for authorization such as accepting , deleting and removing a partner.
app_name = 'Authorize'
urlpatterns = [
         url(r'^$', views.displayDash, name='displayDash'),
         url(r'^admindash$', views.displayAdminDash, name='admindash'),
         url(r'^admindash/proposals$', views.showProposals, name='showproposals'),
         url(r'^admindash/partners$', views.showPartners, name='showpartners'),
         url(r'^admindash/partners/(?P<id>[0-9]+)/remove$', views.removePartner, name='removepartner'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/accept$', views.acceptProposals, name='acceptproposal'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/decline$', views.declineProposals, name='declineproposal'),
         url(r'^partner/checkstatus$', views.checkstatus, name='checkproposal'),
]

dockerfiles/checkin/hotel2-master/HotelApp/urls.py
from django.conf.urls import url
from HotelApp import views
from HotelApp.views import hotelSearch
app_name = 'HotelApp'
urlpatterns = [
     url(r'^$', views.hotelindex, name='hotelindex'),
     url(r'^dashboard/$', views.userDash, name='userDash'),
     url(r'^hotels/(?P<pk>[0-9]+)/$', views.hoteldetails, name='hoteldetails'),
     url(r'^search$', hotelSearch.as_view(), name='hotelsearch'),
     url(r'^(?P<id>[0-9]+)/reviews/create$', views.reviewCreateView.as_view(), name='createreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.reviewUpdateView.as_view(), name='editreview'),
     url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.reviewDeleteView.as_view(), name='deletereview'),
     url(r'^partner/apply$', views.partnerCreateView.as_view(), name='newproposal'),

]

dockerfiles/checkin/hotel2-master/HotelProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from HotelApp import views
#from django_registration.views import RegistrationView
from django_registration.backends.one_step.views import RegistrationView
from HotelProject import settings
from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView


class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/HotelApp/user/'

urlpatterns = [
    url(r'^$', views.home , name = 'home'),
    url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^HotelApp/', include('HotelApp.urls')),
    url(r'^ManageHotels/', include('ManageHotels.urls')),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^Reservations/', include('Reservations.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^social/', include('allauth.urls')),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/login/$', LoginView.as_view(), name ='auth_login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name ='auth_logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dockerfiles/checkin/hotel2-master/Reservations/urls.py
from django.conf.urls import url
from Reservations import views
from Reservations.views import GeneratePDF

# Sets the namespace that can be referred to throughout the django project.
app_name = 'Reservations'
#Urls in regular expression format trigger a view when a url is matched.
urlpatterns = [

    url(r'^book/(?P<hotelid>[0-9]+)/(?P<roomid>[0-9]+)$', views.bookRoom, name='bookroom'),
    url(r"^book/new/(?P<roomid>[0-9]+)/(?P<hotelid>[0-9]+)/(?P<checkin>(\d{4}-\d{2}-\d{2}))/(?P<checkout>(\d{4}-\d{2}-\d{2}))/(?P<totalcost>[0-9]+)$"
    , views.storeBooking, name='newbooking'),
    url(r'^mybookings/$', views.mybookings, name='viewbookings'),
    url(r'^mybookings/cancel/(?P<id>[0-9]+)$', views.cancelbooking, name='cancelbooking'),
    url(r'^mybookings/(?P<id>[0-9]+)/pdf$', GeneratePDF.as_view(), name='gpdf'),
    url(r'^mybookings/sns$',views.bookingsns, name ='bookingsns'),

]

dockerfiles/checkin/hotel2-master/HotelApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from Authorize.models import Partners
# Stores all the hotel details and is used to query hotels.
class Hotels(models.Model):
    Name = models.CharField(max_length  = 255)
    Address = models.CharField(max_length  = 255)
    City = models.CharField(max_length  = 255)
    Country = models.CharField(max_length  = 255)
    TelephoneNumber = models.CharField(max_length=12)
    ImagePath = models.CharField(max_length  = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)
    Description = models.TextField(max_length  = 140)
    Partner = models.ForeignKey(Partners,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = 'Hotels'

    def get_absolute_url(self):
        return reverse('hoteldetails', kwargs={'pk': self.pk})
    def __str__(self):
         return self.Name
# Stores the Hotel reviews and is used to query the reviews
class Review(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE)
    comment = models.CharField(max_length  = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default = 0)
    class Meta:
        verbose_name_plural = 'Review'

    def __str__(self):
         return self.comment
# Stores the Hotels rooms
class Room(models.Model):
    hotel = models.ForeignKey(Hotels,on_delete=models.CASCADE)
    RoomType = models.CharField(max_length  = 255)
    Capacity = models.IntegerField(default = 0)
    BedOption = models.CharField(max_length  = 255)
    Price= models.IntegerField(default = 0)
    View = models.CharField(max_length  = 255)
    TotalRooms = models.CharField(max_length  = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = 'Room'

    def __str__(self):
         return self.RoomType
# Stores and is used to query partner proposals
class Proposal(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    CompanyName = models.CharField(max_length  = 255)
    CompanyEmail = models.EmailField(max_length  = 254)
    HQAddress = models.CharField(max_length  = 255)
    Vision = models.TextField(max_length  = 400)
    class Meta:
        verbose_name_plural = 'Proposal'

    def __str__(self):
         return self.CompanyName

dockerfiles/checkin/hotel2-master/HotelApp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from HotelApp.models import Hotels
from HotelApp.models import Review
from HotelApp.models import Room
from django.views import generic
from django.contrib.auth.decorators import login_required
from django import forms
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse,reverse_lazy
from ManageHotels.models import Photo
from HotelApp.models import Proposal
from django.core.urlresolvers import reverse
from django.views import View
from django.db.models import Q
from Reservations.models import Reservation
import random
from django.db.models import Sum




def home(request):
    return render(request,'HotelApp/home.html')

def userDash(request):
    return render(request,'HotelApp/userDash.html')
@login_required
def hotelindex(request):
    hotels_list = Hotels.objects.all()
    for hotel in hotels_list:
        hotel.thumbnail = Photo.objects.filter(hotel=hotel).first()
    context = {'Hotels': hotels_list}
    return render(request,'HotelApp/showhotels.html',context)

def regcomplete(request):
        link = reverse('HotelApp:userDash')
        return HttpResponseRedirect(link)

def hoteldetails(request, pk):
    theuser = request.user
    #thehotel = Category.objects.filter(id = pk)[0]


    thehotel = Hotels.objects.get(id = pk)
    RecentReservation = Reservation.objects.filter(hotel =  thehotel).filter(user = theuser)

    if RecentReservation:
        allowReview = True
    else:
        allowReview = False

    reviews = Review.objects.filter(hotel=thehotel)
    rooms = Room.objects.filter(hotel=thehotel)
    City = thehotel.City
    NearbyHotels = Hotels.objects.filter(City = City).exclude(id = thehotel.id)
    Nearbyid = []
    for Hotel in NearbyHotels:
        Nearbyid.append(Hotel.id)
    if not Nearbyid:
        Recommendation = None
    else:
        randomid = random.choice(Nearbyid)
        Recommendation = Hotels.objects.get(id = randomid)



    photos = Photo.objects.filter(hotel=thehotel)
    FirstDate = request.session['checkin']
    SecDate =  request.session['checkout']
    current_user = request.user
    for room in rooms:

            RoomsBooked = Reservation.objects.filter(room = room).filter(CheckIn__lte = SecDate,
                                                                        CheckOut__gte = FirstDate)
            count = RoomsBooked.count()
            count = int(count)
            Roomsavailable = room.TotalRooms
            Roomsavailable = int(Roomsavailable)

            Roomsleft = Roomsavailable - count
            room.spaceleft = Roomsleft

    #work out rating
    NumReviews = Reservation.objects.filter(hotel = thehotel).count()
    totalrating = Review.objects.filter(hotel = thehotel).aggregate(sum=Sum('rating'))['sum']
    if totalrating:
        Rating = round(totalrating/NumReviews)
    else:
        Rating = None

    if Rating:        
        if Rating >= 80:
            starpath = '5star.png'
        elif Rating >=  60:
            starpath = '4star.png'
        elif Rating >= 40:
            starpath = '3star.png'
        elif Rating >= 20:
            starpath = '2star.png'
        elif Rating < 20:
            starpath = '1star.png'

    if Rating == None:
        starpath = 'NR.png'




    context = {'hotels': thehotel, 'reviews':reviews,'user':current_user,'rooms':rooms,'Photos':photos,'Recommended':Recommendation,'Rating':Rating,'starpath':starpath,'allowReview':allowReview}
    return render(request, 'HotelApp/hoteldetails.html', context)


class reviewCreateView(CreateView):

    model = Review
    fields = ['comment','rating']
    #success_url = '/hotels/'
    def get_success_url(self):
        hotelid = self.kwargs['id']
        url = reverse('HotelApp:hoteldetails', args=[hotelid])
        return url
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.hotel_id = self.kwargs['id']
        return super(reviewCreateView, self).form_valid(form)

class reviewUpdateView(UpdateView):

    model = Review
    fields = ['comment','rating']
    #success_url = '/hotels/'
    def get_success_url(self):
        reviewid = self.kwargs['pk']
        review = Review.objects.get(id = reviewid)
        hotel = review.hotel
        hotelid = hotel.id
        url = reverse('HotelApp:hoteldetails', args=[hotelid])
        return url
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(reviewUpdateView, self).form_valid(form)

class reviewDeleteView(DeleteView):
    model = Review
    def get_success_url(self):
        reviewid = self.kwargs['pk']
        review = Review.objects.get(id = reviewid)
        hotel = review.hotel
        hotelid = hotel.id
        url = reverse('HotelApp:hoteldetails', args=[hotelid])
        return url
class partnerCreateView(CreateView):

    model = Proposal
    fields = ['CompanyName','CompanyEmail','HQAddress','Vision']
    #success_url = '/hotels/'
    def get_success_url(self):
        url = reverse('HotelApp:userDash')
        return url
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(partnerCreateView, self).form_valid(form)

class hotelSearch(View):
    def get(self,request):
        return render(request, 'HotelApp/search.html')
    def post(self,request):
        Searchterm = request.POST.get("searchterm").title()
	print Searchterm
        NumTravelers = request.POST.get("numtravelers")
	print NumTravelers

        if not Searchterm and not NumTravelers:
            hotels_list = Hotels.objects.all()
        elif Searchterm and not NumTravelers:
            hotels_list = Hotels.objects.filter(Q(City__contains=Searchterm) | Q(Country__contains=Searchterm)
            | Q(Address__contains=Searchterm))
        elif NumTravelers and not Searchterm:
            hotels_list = Hotels.objects.filter(room__Capacity__gte =  NumTravelers)
        elif Searchterm and NumTravelers:
            hotels_list = Hotels.objects.filter(Q(City__contains=Searchterm) | Q(Country__contains=Searchterm)
            | Q(Address__contains=Searchterm)).filter(room__Capacity__gte = NumTravelers)
        Range = request.POST.get("daterange")
	print Range
	print hotels_list
        Rangesplit = Range.split(' to ')
        CheckIn = Rangesplit[0]
        CheckOut = Rangesplit[1]
        request.session['checkin'] = CheckIn
        request.session['checkout'] = CheckOut
        for hotel in hotels_list:
            hotel.thumbnail = Photo.objects.filter(hotel=hotel).first()
        context = {'hotels':hotels_list}
        return render(request, 'HotelApp/showhotels.html', context)

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/form-template.html
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Hotels</title>
    <!-- Styles -->
    <link href="{% static "css/app.css" %}" rel="stylesheet">
    <link href="{% static "css/form.css" %}" rel="stylesheet">

</head>
  <!-- Template for the forms which is used for all the forms on the website. -->
{% for field in form %}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <span class="text-danger small">{{field.errors}}</span>
  </div>
  <label class="control-label col-sm-2">{{ field.label_tag}}</label>
  <div class="col-sm-10"  id="rating">

    {{ field }}
  </div>
</div>

{% endfor %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/home.html
{% extends 'base/landingpage.html' %}
{% block content %}
  <!-- The landing page -->
<div class="title m-b-md">
    Check-In
</div>

<div class="links">

    <a href="{% url 'HotelApp:hotelindex' %}">Hotels</a>

</div>

{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/hoteldetails.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

    <!-- Displays the Hotels Name, Country and City and Company Name -->
      <div class="page-header">

          <h2>{{hotels.Name}} <small class="text-muted">- <u>{{hotels.Partner.CompanyName}}</u></small>

          </h2>
          <small>{{ hotels.Country}} |  {{ hotels.City}}</small>
      </div>
      <!-- Slideshow of all the Hotels Photos -->
      <center>

        <div class="autoplay">
          {%for Photo in Photos|slice:"1:"%}
          <div><img  src="{{MEDIA_URL}}{{Photo.path}}"></div>
          {%endfor%}
        </div>
    </center>
      <!-- End Slideshow -->

    <!-- Information Box , Hotel details ( Address, Tel etc ) & Hotel Rating-->
    <hr>
    <div class= "panel panel-primary">

      <div class = "panel-heading">
        <h3 class="panel-title">Hotel Details:</h3>
      </div>

      <div class="panel panel-body">

          <dl class="row">
              <dt class="col-sm-5">Check-In User Rating:</dt>
                <dd class="col-sm-7">
                    <img src="{%static starpath %}" /> <!-- Star path-->
                    {% if Rating %}
                    <b>{{Rating}}%</b>
                    {% else %}
                    <b>Not Rated</b>
                    {% endif %}
                </dd>
              <dt class="col-sm-5">Address:</dt>
                <dd class="col sm-7">
                    {{ hotels.Address}}
                </dd>
              <dt class="col-sm-5">Telephone Number:</dt>
                <dd class="col sm-7">
                    {{ hotels.TelephoneNumber}}
                </dd>
        <!-- Unless there is only 1 hotel in this City , Display a recommended Hotel. -->
                <dt class="col-sm-5">Other Hotels Nearby:</dt>
                <dd class="col sm-7">
                    {% if Recommended %}
                      <a href="{% url 'HotelApp:hoteldetails' Recommended.id %}">{{Recommended.Name}}</a>
                    {% else %}
                    <p>
                      No other nearby Hotels.
                    </p>
                    {% endif %}
                </dd>

        </dl>

  </div>
</div>
<hr />
<div class= "panel panel-primary">

  <div class = "panel-heading">
    <h3 class="panel-title ">Weather information about <b>{{hotels.City}}</b>:</h3>

  </div>

  <div class="panel panel-body">
            <div class="text-center">
              <b>Current Temperature</b>
              <p id="temp"></p>
              <img id="icon"  src="" />
            </div>
            <div class="text-center">
              <b>Current Weather</b>
              <p id="weather">
              </p><p id="desc"></p>
            </div>
            <div id="info">
            </div>





</div>
</div>

<hr>
      <!-- Displays a list of all Rooms that this Hotel Offers and the rooms information. -->
      <h4>Rooms:</h4>
      {% if rooms %}

        {% for room in rooms %}




        <h5><u> {{room.RoomType}}</u></h5>
        <p><mark>Max Occupants :</mark>  {{room.Capacity}} People.</p>
        <p><mark>Beds Provided :</mark> {{room.BedOption}}.</p>
        <p><mark>View :</mark> {{room.View}}.</p>
        <p><mark>Price :</mark> £{{room.Price}}</p>
        <p><b>Rooms Left: </b>{{room.spaceleft}}</p>

        {% if room.spaceleft > 0 %}

        <a href="{% url 'Reservations:bookroom' hotels.id room.id %}" class="btn btn-success">Book</a>
        <hr />
        {% endif%}
       {% endfor %}
      {%endif%}

          <!-- If Room has more than 0 rooms , Display a button to book the room.

           -->



<!-- Displays a table with all the reviews of the hotel that users have left. -->

<h4>Reviews:</h4>

<table class="table">

      <thead>
        <tr>
        <th>User</th>
        <th>Comment</th>
        <th></th>
        </tr>
      </thead>
      <tbody>
      {% if reviews %}

        {% for review in reviews %}

          <tr>
              <td><a class="" href="#">{{review.user.username}}:</a></td>
              <td>{{review.comment}}</td>
              <!-- If the User that Posted the review and the current user match , display an edit and Delete button.-->
                {% if review.user_id == user.id %}
                  <td><a class="btn btn-default pull-right btn-sm" href="{% url 'HotelApp:editreview' review.id %}">Edit Review</a></td>

                  <td>
                    <form action="{% url 'HotelApp:deletereview' review.id %}" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}

                        <button type="submit" class="btn btn-danger pull-right btn-sm">Delete Review</button>
                      </form>

                  </td>

                  {% else %}
                    <td></td>
                    <td></td>
                  {%endif%}

          </tr>

        {% endfor%}
      {% endif %}
      </tbody>
</table>
<hr>

<!-- If the User has made a booking with the current hotel , display a Add review form. -->
{% if allowReview == True %}
<a class="btn btn-info pull-right btn-sm" href="{% url 'HotelApp:createreview' hotels.id %}">ADD Review</a>
{% endif %}

<!-- If Laravel Validation detects errors then this will show a message. -->

</div>
</div>

{% endblock %}

<!-- The scripts for the page are included below , Slideshow / Rating -->
{% block scripts %}

  <script src="{% static "js/slick.js" %}"></script>
  <script>

      $('.autoplay').on('init',function(slick){
        console.log('fired');
        $('.autoplay').fadeIn(300);
      })
      .slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2500,
        arrows:false,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear',
        lazyLoad:'ondemand'

      });

  </script>


  <script>

      var City = "{{hotels.City}}";
        function ascii (a) { return String.fromCharCode(a); }
        function displayweather(data){
          if (data.length !== 0){
                var mainweather = (data.weather[0].main);
                var desc = (data.weather[0].description);
                var temp = (data.main.temp);
                var code = (data.weather[0].icon)
                var hum = (data.main.humidity)
                var matemp = (data.main.temp_max)
                var Wind= (data.wind.speed)
                var img = "http://openweathermap.org/img/w/"+code+".png"
                console.log()
                var main = $('<p>').appendTo('#weather').text(mainweather + " | " +desc);
                var temp = $('<p>').appendTo('#temp').text(temp +  ascii(176) +"C");
                var humidity = $('<p>').appendTo('#info').text("Humidity:"+"   "+hum+"%"+"  -   "+ " Max Temp: "+matemp+" "+ ascii(176) +"C" +"  -  "+" Wind Speed: "+Wind+ "Mph");
              //  var mintemp = $('<p>').appendTo('#info').text("Min Temp: "+mitemp+ ascii(176) +"C");
              //  var wspeed = $('<p>').appendTo('#info').text("Wind Speed: "+Wind+ "Mph");
                $("#icon").attr("src",img) }
              else{
                var error = $('<p>').appendTo('#info').text("Sorry , We have been unable to retrieve live weather information");
              }
        }



      $(document).ready(function() {


        $.getJSON("http://api.openweathermap.org/data/2.5/weather?q="+ City +"&units=metric&APPID=ae9512f4de94ef9415b53d6a357bd78a",displayweather);




        })


  </script>



{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/hotels_form.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- A form for creating , updating and deleting hotels -->
<form class="form-horizontal" action="" method="post">
{% csrf_token %}
{% include 'HotelApp/form-template.html'%}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-success">submit</button>
  </div>
</div>


</form>


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/proposal_form.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- A form for users to submit partner proposals -->
<form class="form-horizontal" action="" method="post">
{% csrf_token %}
{% include 'HotelApp/form-template.html'%}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-success">submit</button>
  </div>
</div>


</form>


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/review_form.html
{% extends 'base/base.html' %}

{% load staticfiles %}
{% block scripts %}
<script src="{% static "/js/star-rating.js" %}" type="text/javascript"></script>
<script>
    // Manipulates the rating field in the form to display as stars.
    var Rating = document.getElementById('id_rating');
    Rating.type = "hidden";
    Rating.setAttribute("data-stop","100")
    Rating.setAttribute("data-step","20")
    Rating.className = "rating";

    $("#id_rating").rating()
    var p = document.getElementsByTagName("span")[6]
    p.className = "ratingstar";


</script>
{%endblock%}

{% block content %}

<form class="form-horizontal" action="" method="post">
{% csrf_token %}
{% include 'HotelApp/form-template.html'%}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-success">submit</button>
  </div>
</div>


</form>



{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/room_form.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- A form used to add , edit and delete rooms-->
<form class="form-horizontal" action="" method="post">
{% csrf_token %}
{% include 'HotelApp/form-template.html'%}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-success">submit</button>
  </div>
</div>


</form>


{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/search.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Advanced Search -->

<div class="container">
    <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <h1 class="text-primary">Hotel Search</h1>
            <form method="POST"  action="" enctype="multipart/form-data" name="search" onsubmit="return validateForm()">
              {% csrf_token %}

            <div class="form-group">

                    <label class="form-group-label text-muted" for="checkin">Enter a Destination,Hotel, Landmark or address:</label>
                    <input class="form-control" type="text" name="searchterm" id="checkin"  placeholder="Search..">
            </div>
            <!-- Multi Date , Date Picker -->
            <div class="form-group">
                  <label class="text-muted" for="checkin">Please Select Your Check-In and Check-Out dates:</label>
                  <input  class="date form-control" type="text" name="daterange" id="checkin"  placeholder="Select Date.." required>
            </div>
            <div class="form-group">

                  <label  class="text-muted" for="travelers">Travelers:</label>
                  <select  name="numtravelers" class="form-control">
                    <option></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                  </select>
            </div>

            <br />
            <button type="submit" class="btn btn-primary">Search</button>
            </form>
          </div>



    </div>

</div>



{% endblock %}
<!-- Scripts for the Date picker and Form validation  -->
{% block scripts %}
  <script src="https://unpkg.com/flatpickr"></script>

  <script>

  flatpickr(".date", {

	minDate: "today",
  mode:"range",

});

function validateForm() {
  var setdate = document.forms["search"]["daterange"].value;
  if(setdate == ""){
    alert("Date Must be Filled Out");
    return false;
  }
}




</script>
{% endblock %}

dockerfiles/checkin/hotel2-master/templates/django_registration/HotelApp/userDash.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}



<!-- Displays the Customer/user Dashboard -->

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Dashboard  |   You are logged in! {{user.username}}</div>

                <div class="panel-body">
                  <div class="list-group">
                    <a href="{% url 'HotelApp:hotelsearch'%}" class="list-group-item">Make a Booking</a>
                    <a href="{% url 'Reservations:viewbookings'%}" class="list-group-item">View Your Bookings</a>
                </div>
            </div>
            <hr>
            <div class="panel panel-default">
              <!-- Users can become partners on the website -->
                <div class="panel-heading">Want to Partner with Check-in.com?</div>

                <div class="panel-body">
                  <div class="list-group">
                    <a href="{% url 'HotelApp:newproposal'%}" class="list-group-item">Become a Partner Now!</a>
                    <a href="{% url 'Authorize:checkproposal'%}" class="list-group-item">Check your proposal status</a>
                  </div>

                </div>
            </div>


        </div>

    </div>

</div>
{% endblock %}